### ISSUE TITLE
linux binaries does not work on ubuntu 20.04 due to GLIBC version requirement

### ISSUE THREAD

**Issue by franko** [pragtical/pragtical#13]
ubuntu 20.04 is three years old and it is already too old ? :-)

Normally what people say for linux binaries is to compile on an old distribution like for example ubuntu 18.04. In this way the binaries will works just fine in almost any distribution except the very old ones.

**Comment by jgmdev** [comment]
Yeah, for that takase did some custom container to produce the builds using an older distro image but when I forked everything from lite-xl to pragtical dropped it since I was feeling lazy on also incorporating the custom container :smile:  

I wonder if we could switch instead to something like musl to produce fully static linux builds as done on the plugin manager https://github.com/pragtical/plugin-manager/blob/master/.github/workflows/build.yml#L23 that way we don't have to worry about incompatibilities with the libc runtime.
