### ISSUE TITLE
CJK (Unicode) filename support on Windows

### ISSUE THREAD

**Issue by Vinfall** [pragtical/pragtical#136]
### Problem

Pragtical cannot open files with CJK (or probably non-ASCII/Unicode) characters in filename, either in tree view, drag & drop or (idk the name but I call it) open file palette on Windows.

### Steps to reproduce

1. Run pragtical
2. try to open a file with CJK filename
3. Error

### More details

I checked TODO List & issues but cannot find anything related. In Lite-XL I found [Unicode filename support #861](https://github.com/lite-xl/lite-xl/issues/861) that's probably related. Not sure why it still persists in pragtical.

Note that I'm not asking for general Unicode support (display Unicode chars correctly by default), which can be solved by loading more fonts, but simply a request to fix the error when opening CJK-named files.

### What I tried

- Run in Void Linux (tarball & AppImage), works
- Drag and drop, as suggested in the linked issue, the issue persists
- Disable all plugins, persists, can't load JetBrains font BTW

### Log

I don't know why, but `error.txt` only got written when I tried to open in tree view. Drag & drop does not write to it and throw a slightly different error.

`error.txt`:
<details><summary>Details</summary>
<p>

```lua
Error: D:\Linux\Obsidian\计划.md: No such file or directory

stack traceback:
	[C]: in function 'error'
	D:\path\to\pragtical\data/compat\module.lua:214: in function 'assert'
	D:\path\to\pragtical\data/core\doc/init.lua:101: in function 'load'
	D:\path\to\pragtical\data/plugins\autoreload.lua:136: in function 'load'
	D:\path\to\pragtical\data/core\doc/init.lua:33: in function 'new'
	D:\path\to\pragtical\data/plugins\detectindent.lua:303: in function 'new'
	D:\path\to\pragtical\data/core\object.lua:77: in function 'Doc'
	D:\path\to\pragtical\data/core/init.lua:1122: in function 'open_doc'
	D:\path\to\pragtical\data/core/init.lua:525: in function 'init'
	[string "local core..."]:14: in function <[string "local core..."]:6>
	[C]: in function 'xpcall'
	[string "local core..."]:6: in main chunk
```

</p>
</details>

**Comment by jgmdev** [comment]
As far as I remember a [patch](https://github.com/pragtical/pragtical/blob/master/resources/windows/001-lua-unicode.diff) was introduced into Lua 5.4  to allow its internal io library to properly handle such files properly under windows. 

We use LuaJIT by default instead of Lua, and it seems that LuaJIT has the same issue with these file names... (I wonder if there is a way to solve this on LuaJIT without having to patch it or if there exists a io drop in replacement library that properly works with encodings on windows...) For the moment and if interested I would say to configure with `-Djit=false`  to build the editor using PUC Lua and use the unicode patch as done here: https://github.com/pragtical/pragtical/blob/master/scripts/build.sh#L186

**Comment by jgmdev** [comment]
Rebased the unicode patch for LuaJIT and seems to be properly opening non ASCII files, could you give it a try by applying #138? You would need to build pragtical with msys2 since msvc was giving issues described on the PR. The dependencies needed when building with msys2 are listed here https://pragtical.dev/docs/setup/building#windows-msys2

You can also build by forcing subproject fallbacks:

```sh
# Configure with forcefallback and disable package manager for faster build
meson setup --wrap-mode=forcefallback -Dppm=false build

# Build
meson compile -C build

# Run
./scripts/run-local build
```

**Comment by jgmdev** [comment]
Fixed msvc build and tested CI builds. Opening files with unicode characters on the filename should now be possible. Thanks for Reporting!

**Comment by Vinfall** [comment]
Did not compile yesterday as I work mostly offline and msys2/meson cannot download deps for building :(

Confirmed working using latest rolling based on https://github.com/pragtical/pragtical/commit/a9631b2b7c5965bcb1e04fb0a06057cde0100cb1 & https://github.com/pragtical/pragtical/actions/runs/10516832091. Many thanks!
