### ISSUE TITLE
Launching from command line but reusing an existing window

### ISSUE THREAD

**Issue by quesada** [pragtical/pragtical#165]
I have pragtical open, and want to edit a file, Launching from command line but reusing an existing window.
In other editors, there's a flag for it (for example, in Textadept there's -f).
Is there something similar in pragtical?

**Comment by jgmdev** [comment]
Make sure that **Single Instance** is enabled on the ipc plugin settings (should be enabled by default):

![ipc-single-instance](https://github.com/user-attachments/assets/662f3e76-9537-4ee3-b938-d6f57482afde)

With an already opened window of the editor on your terminal just type:

```sh
pragtical /path/to/file.ext
```

It should raise the existing editor instance with the specified file, note that on some environments (Linux + Wayland) the window will not be automatically raised up because of missing focus protocol or other discrepancies. The raise window implementation is here: https://github.com/pragtical/pragtical/blob/master/src/api/system.c#L749.

**Comment by jgmdev** [comment]
Now documented on: https://pragtical.dev/docs/user-guide/cli#using-already-opened-instance
