### ISSUE TITLE
Settings: Add feature to define standard directory

### ISSUE THREAD

**Issue by ShalokShalom** [pragtical/pragtical#25]
I think many desire a path to be set, that from which Pragtical does launch. Currently, it shows all the content from my home directory, including all the hidden parts. 

That is surely useful for many, and looks just messy for my usecase, personally. 
I know that I can launch pragtical with a path from the commandline, and I consider that not pragtical enough ;)

**Comment by SwissalpS** [comment]
"Open Directory With.." from file manager works 'fine' for me.

I do support the idea though of setting another default directory and I'm wondering if this isn't already possible. Certainly something that upstream Lite-XL could use too.

**Comment by ShalokShalom** [comment]
You can do `pragtical /path/` from the command line, and I am looking for a UI way.

**Comment by SwissalpS** [comment]
you could add the path to your litexl.desktop file  (if you're using an OS that uses *.desktop files)
any number of slightly different named *.desktop files are possible, each with their own base-path.

**Comment by ShalokShalom** [comment]
I guess so. This would still not provide a UI way to do this.

**Comment by jgmdev** [comment]
Is this related to first-time editor launch opening home dir (since the workspace plugin remembers your last opened project directory)? Because another option could be not opening any directory on first-time launch and just displaying the welcome screen, which would allow you to open any project. 

The only issue is various plugins that depend on a root project directory to always be available/open would need to be adapted to check if a project is loaded before trying to apply any functionality. But it is doable, we would just break compatibility with Lite XL even more.

Another possibility could be calling into the native File Browser dialog of the OS before loading any plugins to let the user choose a project directory on first-time launch and then proceed to normal startup, but that would be wonky :)

**Comment by ShalokShalom** [comment]
To be honest, I feel like the smoothest method is, to disable hidden files by default. 
OR, if that is more your taste, to display them below the non-hidden files. 

Otherwise, I would think a "Show hidden files" option in the context menu of the treeview would make sense..

**Comment by jgmdev** [comment]
> To be honest, I feel like the smoothest method is, to disable hidden files by default.

Done https://github.com/pragtical/pragtical/commit/ecda0a0ab7ff1c4f4795bb7af745ab728b5a6798

**Comment by ShalokShalom** [comment]
Would you merge the context menu addition?

**Comment by jgmdev** [comment]
> Would you merge the context menu addition?

Feel free to submit the PR, the feature to `show/hide hidden files` directly from TreeView context menu would be useful to have so why not :) and maybe another option to also toggle `ignored files` would be welcome.

**Comment by SwissalpS** [comment]
> I feel like the smoothest method is, to disable hidden files by default.

I don't understand what this has to do with setting default path and how that treeview patch closes this issue.

Maybe writing a launcher would work too. Start up the launcher which asks for the project directory you want and then have the launcher init pragtical with the chosen path as parameter -> no need to make plugins aware of anything.

IIRC liteXL has a feature to change project dir. I guess it then reloads the plugins.

**Comment by ShalokShalom** [comment]
> I don't understand what this has to do with setting default path and how that treeview patch closes this issue.

Because it was messy before. I did not state this explicitly, but the only reason I wanted to change the default directory, was because the hidden files cluttered everything.  

> Feel free to submit the PR

I will look into that.
