### ISSUE TITLE
Behavior when file is being modified by an external process

### ISSUE THREAD

**Issue by iahung3** [pragtical/pragtical#81]
Other text editors will notify you and ask you if you want to reload the file from disk or keep the current content and mark the file as changed (this is configurable). Pragtical will auto-reload the file without notifying me that the file is being modified by an external process.

**Comment by jgmdev** [comment]
Yeah, that default behavior is annoying, I totally forgot about it because I have the always ask flag turned on https://github.com/pragtical/pragtical/blob/master/data/plugins/autoreload.lua#L10

I guess it should be set to true by default for the safetyness of the editing session, what do you think?

**Comment by iahung3** [comment]
> Yeah, that default behavior is annoying, I totally forgot about it because I have the always ask flag turned on https://github.com/pragtical/pragtical/blob/master/data/plugins/autoreload.lua#L10
> 
> I guess it should be set to true by default for the safetyness of the editing session, what do you think?

I think it should be set to true.
