### ISSUE TITLE
Macos terminal inside pragtical doesn't pre-configure the available executable commands

### ISSUE THREAD

**Issue by RohanVashisht1234** [pragtical/pragtical#85]
The zsh terminal of practical inside macos is unable to recognize yarn or any other program which has been exported properly.

```st
rohanvashisht@Rohans-MacBook-Air dir_name % yarn                                                  
zsh: command not found: yarn
```

```st
rohanvashisht@Rohans-MacBook-Air dir_name % npm                                                  
zsh: command not found: npm
```

Somehow it does recognize commands like gcc and clang.

**Comment by jgmdev** [comment]
My guess would be that you installed those commands using brew or macports which usually install them into `/usr/local/bin`   (you can corroborate this by running `which yarn` on the OS terminal application), and that location is not getting globally added in the `PATH` environment variable (as I have experienced with the LSP plugin). Until this is fixed on the terminal plugin (or the editor it self) you could try the following to see if it fixes it for you:

1. On pragtical, open the Command Palette
2. Search for `Core: Open User Module` and run it
3. Paste the following into an appropriate section of the opened lua user module file, save and restart the editor:

```lua
local system_path = os.getenv("PATH")
system_path = "/usr/local/bin:" .. system_path
system.setenv("PATH", system_path)
```

4. Check if the `PATH` environment variable was properly updated by opening the built-in terminal plugin and executing `echo $PATH`
5. If `/usr/local/bin:` was prepended, try running any of the previously failing commands again.

Maybe I should incorporate the fix above on Pragtical it self when the platform been run is Mac OS X instead of having to fix it on every plugin that depends on this...
