### ISSUE TITLE
commands when run inside macos terminal in pragtical display a big font size (not related to font size of other things in the terminal)

### ISSUE THREAD

**Issue by RohanVashisht1234** [pragtical/pragtical#86]
### The following image best describes the issue:
<img width="830" alt="image" src="https://github.com/pragtical/pragtical/assets/81112205/794afb71-7a54-4de8-85ce-91de7bca2632">

**Comment by jgmdev** [comment]
I would need to investigate this properly on my Mac machine but, could you test by enforcing a font on the terminal plugin settings as shown on the image below?

![terminal-settings](https://github.com/pragtical/pragtical/assets/1702572/0b8dd494-60a3-457a-8edf-54406099ebd9)

If the steps above fix the issue they could could hint what is causing it...

**Comment by jgmdev** [comment]
While upgrading the terminal plugin to latest changes from upstream I was finally able to reproduce this issue and found out the cause was the font used for bold text not getting synchronized to scale changes.

Made some changes to plugin to update the bold font accordingly which should now result on correct font size.
