### ISSUE TITLE
Handring of Encodings that replaces Backslash

### ISSUE THREAD

**Issue by Hinaxnitro** [pragtical/pragtical#94]
I'm using this editor on Japanese Windows to write C (MSVC) code.

Since Japanese defaults Shift_JIS, a Backslash character `0x52` on Japanese font shows as a Yen sign.
(display only, behavior in programs are as same as Backslash)
But when I load a Shift_JIS file, the editor converts `0x52` characters to Unicode's Yen sign.
This breaks things that rely on Backslash (like LSP).
![2024-0618-131623(1022x736)](https://github.com/pragtical/pragtical/assets/72604007/50617a6d-9b9a-4c1d-839c-0bbf384594bb)

**Comment by jgmdev** [comment]
This patch fixes it, but...

```diff
diff --git a/data/core/doc/init.lua b/data/core/doc/init.lua
index edc17cd1..7c325f80 100644
--- a/data/core/doc/init.lua
+++ b/data/core/doc/init.lua
@@ -84,6 +84,20 @@ function Doc:set_filename(filename, abs_filename)
 end
 
 
+---@param encoding string
+---@param content string
+---@return string fixed_content
+local function ecoding_conversion_fixes(encoding, content)
+  if encoding == "SHIFT_JIS" then
+    -- on Japanese \ is shown as Yen sign ¥, iconv do this conversion
+    -- which is problematic because it changes the original codepoint,
+    -- we are insterested on keeping the original to prevent issues on
+    -- code that uses escape sequences like '\n', '\r', etc...
+    content = content:ugsub("¥", "\\")
+  end
+  return content
+end
+
 function Doc:load(filename)
   if not self.encoding then
     local errmsg
@@ -108,6 +122,7 @@ function Doc:load(filename)
       strict = false,
       handle_from_bom = true
     }))
+    content = ecoding_conversion_fixes(self.encoding, content)
     for line in content:gmatch("([^\n]*)\n?") do
       if line:byte(-1) == 13 then
         line = line:sub(1, -2)

```

Here comes the but... I wonder if this would be the correct behavior since a legitimate ¥ codepoint would also get converted back to a \\. Do you think such a fix would cause issues? Is it safe to always convert ¥ to \\ ? I ask because I'm not familiar with the language. Sounds to me like this issue should be redirected to the iconv library since it shouldn't be doing such conversion when the ¥ character already has a specific codepoint and japanese fonts do the conversion automatically as you mentioned.

If it isn't safe to always convert ¥ to \\, wouldn't it be better to switch to utf-8 encoding for coding purposes and leave SHIFT_JIS for other text editing activities non-code related?

Anyways, I smell this to be improper behavior from the iconv library side...

**Comment by jgmdev** [comment]
Was curious and searched a bit of history around this issue, leaving it here for future reference:

> In Shift-JIS (a variant of JIS X 0208), the character `¥` (Yen sign) has a special representation. In the encoding scheme, `¥` is encoded as `\x81\x9F`. This might seem unusual, but it's because the original design of Shift-JIS was influenced by the way Japanese characters were represented in older systems.
> 
> In pre-1980s Japan, the Yen sign (`¥`) was often represented using a combination of ASCII characters: `\\` (backslash-backslash). To accommodate this convention, the designers of Shift_JIS decided to encode `¥` as `\x81\x9F`, which is equivalent to the original `\\` representation.
>
> When you use `iconv` with Shift_JIS encoding and pass a string containing `\`, it attempts to convert it according to the rules defined for that encoding. In this case, since `\` has a special meaning in Shift-JIS (representing `¥`), `iconv` replaces the original `\` characters with the equivalent ¥ character (`\x81\x9F`).

Added a proper fix on #106 which replaces every \\ into a special char sequence that after conversion to a ¥ gets converted back to a \\. Will merge right away since this solution shouldn't cause any issues (I think :smile:).

Thanks for reporting!

**Comment by Hinaxnitro** [comment]
Sorry for comment, but this solution seems having issues when multi-byte characters are shown.

![right one is Pragtical](https://github.com/user-attachments/assets/6635b7e8-0904-4576-b4e1-3b1a7b4dbbc8)

(text from [https://www.type-labo.jp/KumimihonREAD.html](https://www.type-labo.jp/KumimihonREAD.html))

**Comment by jgmdev** [comment]
> Sorry for comment, but this solution seems having issues when multi-byte characters are shown.

@Hinaxnitro
Could you please try this change on core/encoding.lua and let me know if it fixes it for you?

```diff
diff --git a/data/core/encoding.lua b/data/core/encoding.lua
index 51adf9e4..bf4f5252 100644
--- a/data/core/encoding.lua
+++ b/data/core/encoding.lua
@@ -9,7 +9,7 @@ encoding.convert = function(tocharset, fromcharset, text, options)
     -- we are insterested on keeping the original to prevent issues on
     -- code that uses escape sequences like '\n', '\r', etc...
     local errmsg
-    text = text:gsub("\\", "{\\\\\\}")
+    text = text:ugsub("\\", "{\\\\\\}")
     text, errmsg = encoding_convert(tocharset, fromcharset, text, options)
     if text then
       text = text:gsub("%{¥¥¥%}", "\\")
```

Also could you open a new issue for this with a title like:

```
Wrong replacement of backslashes belonging to multi-byte sequences in Shift_JIS
```

And also link it to this issue by adding #94 as part of the description
